### ISSUE TITLE
otwieranie przez internety

### ISSUE THREAD

**Issue by Tusionator** [so-sonia/AsystentGotowaniaApp#2]
todos

**Comment by Tusionator** [comment]
klasa RecipeFromLink czeka na Twoje uzupełnienie ;) 
Dałam JSON jako formę przekazania przepisu do głównego activity - myślę, że łatwo będzie dzięki temu ewentualnie w przyszłości dodać zdjęcia :)

Rób magię :D

**Comment by so-sonia** [comment]
gotowe nie działa tylko kwestia smaku, ale to musi być wina po ich stronie, bo nie chce nawet nawiązać połączenia
